language: java

# "dist" is specified for openjdk6 and oraclejdk7 because the new images (Ubuntu
# Trusty 14.04) do not support them. Specifying "group: deprecated-2017Q3" does
# not help.
# See <https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879>
# and <https://blog.travis-ci.com/2017-08-29-trusty-image-updates>.

matrix:
  include:
   - jdk: openjdk6
     dist: precise
     env: EXTRA_OPTIONS='-pl !elk-owlapi,!elk-owlapi-standalone,!elk-protege,!elk-distribution'
   - jdk: oraclejdk7
     dist: precise
   - jdk: openjdk7
   - jdk: oraclejdk8

install: mvn install -DskipTests=true $EXTRA_OPTIONS

script: mvn test -Dassembly.skipAssembly=true -B $EXTRA_OPTIONS

